<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" id="logo"/>
        </div>

        <div class="row mb-3">
          <div class="col">
            <h2>Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row pb-5">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block" id="button">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  