<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-left">
          <a href="/" class="card-link">Voltar</a>
        </div>

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" id="logoIndex"/>
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" class="form-control" value="<?=(isset($this->view->usuario['nome']) && !empty($this->view->usuario['nome']))?$this->view->usuario['nome']:''?>" name="name"  required placeholder="Nome">
              </div>

              <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" value="<?=(isset($this->view->usuario['email']) && !empty($this->view->usuario['email']))?$this->view->usuario['email']:''?>" required placeholder="E-mail">
                <small id="email" class="form-text text-muted">Nunca vamos compartilhar seu email, com ninguém.</small>
              </div>

              <div class="form-group">
                <input type="password" class="form-control" name="pass" required placeholder="Senha">
              </div>

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" id="button" class="btn btn-primary btn-block">Inscrever-se</button>
              <?php if($this->view->erroCadastro): ?>

                <small class="form-text text-danger mt-3">
                  *Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente!
                </small>


              <?php endif; ?>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>